version: 2.1
jobs:
    build:
        docker:
            -   image: circleci/node:11.9.0

        working_directory: ~/repo

        steps:
            - checkout

            # Download and cache dependencies
            -   restore_cache:
                    keys:
                        - v1-dependencies-{{ checksum "package.json" }}
                        # fallback to using the latest cache if no exact match is found
                        - v1-dependencies-
            - run: 'sudo npm install -g npm@latest'

            - run: npm install

            -   save_cache:
                    paths:
                        - node_modules
                    key: v1-dependencies-{{ checksum "package.json" }}

            - run: ls -ltra

            - run: pwd

            - run:
                name: Deploy to gh-pages
                command: |

                    GIT_REPO="git@github.com:velopaymentsapi/VeloOpenApi.git"

                    rm -rf ./node_modules/gh-pages/.cache

                    if [ $CIRCLE_BRANCH == "master" ]
                    then
                        echo "Running on Master"
                        npm run build

                        echo "Deploying"
                        npm run deploy -r $GIT_REPO
                    elif [ $CIRCLE_BRANCH != "master" ] && [ $CIRCLE_BRANCH != "gh-pages" ]
                    then
                        echo "Running NOT on master or gh-pages"
                        npm run build

                        DEST_DIR="/branch/$CIRCLE_BRANCH"

                        echo "Deploying to branch $DEST_DIR on $GIT_REPO"



                       NPM_CONFIG_GIT_REPO=GIT_REPO  NPM_CONFIG_DEST_DIR=DEST_DIR npm run deploy
                    else
                        echo Should not get here
                    fi
workflows:
    version: 2
    build-deploy:
        jobs:
            - build:
                  filters:
                      branches:
                          ignore:
                              - gh-pages