version: 2.1
jobs:
    build:
        docker:
            -   image: circleci/node:11.9.0

        working_directory: ~/repo

        steps:
            - checkout
workflows:
    version: 2
    build-deploy:
        jobs:
            - build:
                  filters:
                      branches:
                          ignore:
                              - gh-pages
