# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
    build:
        docker:
            # specify the version you desire here
            -   image: circleci/node:11.9.0

            # Specify service dependencies here if necessary
            # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
            # - image: circleci/mongo:3.4.4

        working_directory: ~/repo

        steps:
            - checkout

            # Download and cache dependencies
            -   restore_cache:
                    keys:
                        - v1-dependencies-{{ checksum "package.json" }}
                        # fallback to using the latest cache if no exact match is found
                        - v1-dependencies-
            - run: 'sudo npm install -g npm@latest'

            - run: npm install

            -   save_cache:
                    paths:
                        - node_modules
                    key: v1-dependencies-{{ checksum "package.json" }}

            - run: ls -ltra

            - run: pwd

            - run:
                name: Deploy to gh-pages
                command: |

                    GIT_REPO="git@github.com:velopaymentsapi/VeloOpenApi.git"

                    if [ $CIRCLE_BRANCH == "master" ]
                    then
                        echo "Running on Master"
                        npm run build

                        echo "Deploying"
                        npm run deploy -r $GIT_REPO
                    elif [ $CIRCLE_BRANCH != "master" ] && [ $CIRCLE_BRANCH != "gh-pages"]
                    then
                        echo "Running NOT on master or gh-pages"
                        npm run build

                        DEST_DIR="<branch/$CIRCLE_BRANCH>"

                        echo "Deploying to branch $DEST_DIR"

                        npm run deploy -r $GIT_REPO -e $DEST_DIR
                    fi
workflows:
    version: 2
    build-deploy:
        jobs:
            - build:
                  filters:
                      branches:
                          ignore:
                              - gh-pages