type: object
required:
    - name
properties:
    name:
        type: string
        description: The name of the application.
        minLength: 2
        maxLength: 100
    description:
        type: string
        description: Description of the application.
        minLength: 2
        maxLength: 1024