post:
    summary: Create Application
    description: Create an application for the given Payor ID
    operationId: payorCreateApplicationRequest
    tags:
        - Payor Service
    parameters:
        - name: payorId
          in: path
          description: Payor ID
          required: true
          schema:
              type: string
              format: uuid
    x-code-samples:
        - lang: 'shell'
          source: |
                $ curl 'https://api.sandbox.velopayments.com/v1/payors/79a6fdaa-f4bb-47b7-9c1f-f6fd99c156a0/applications' -i -X POST \
                    -H 'Content-Type: application/json' \
                    -H 'Authorization: Bearer 93560bbb-5e79-492a-97b5-1ffbdf1cfeb8' \
                    -d '{"name":"foo","description":"a foo application"}'
    requestBody:
        description: Details of application to create
        required: true
        content:
          application/json:
            schema:
              $ref: ../definitions/model/PayorCreateApplicationRequest.yaml
    responses:
        '202':
            description: HTTP Accepted
            headers:
                location:
                    schema:
                        type: string
                        description: URI of created application
            example: |
                HTTP/1.1 202 Accepted

        '404':
            description: Payor Id Not Found